Repository wecode-bootcamp-korea/30-1st-chadamhwa-backend, pull requests merged in 2022-03, with the labels that each got.

#3 [30기 임정찬, 안성준] 회원가입, 로그인, 데코레이터 추가
  chadamhwa/urls.py
  requirements.txt
  users/urls.py
  users/views.py
  utils/login_required.py
  utils/validation.py
Labels: Status: 리뷰 요청

#4 카트DB에 타임스탬프 모델 추가
  orders/migrations/0003_cart_created_at_cart_updated_at.py
  orders/models.py
Labels: Status: 리뷰 요청

#7 [30기 임정찬] DB 초기화
  .gitignore
  drinks/migrations/0001_initial.py
  drinks/migrations/0002_rename_image_drinkimage_alter_drinkimage_table.py
  drinks/models.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_alter_orderitem_order_number.py
  users/migrations/0001_initial.py
Labels: Status: 리뷰 요청

#2 [30기 박영서] Create: 필터링 기능 구현
  .gitignore
  chadamhwa/urls.py
  drinks/urls.py
  drinks/views.py
Labels: Status: Conflict 해결 요청

#6 [30기 안성준] 장바구니 기능 추가
  .gitignore
  chadamhwa/urls.py
  orders/urls.py
  orders/views.py
  users/views.py
Labels: Status: Accepted

#9 [30기 박영서] feature/mainpage
  drinks/urls.py
  drinks/views.py
Labels: Status: 리뷰 요청

#10 [30기 안성준] 장바구니 path parameter 수정
  orders/urls.py
  orders/views.py
Labels: Status: 리뷰 요청

#5 [30기 임정찬] Feature/review
  .gitignore
  chadamhwa/settings.py
  chadamhwa/urls.py
  drinks/models.py
  drinks/urls.py
  drinks/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/urls.py
  reviews/views.py
Labels: Status: 리뷰 요청
